Repository Radu-Raicea/SignalAndroid, pull requests merged in 2018-02, with the labels that each got.

#15 Pinned messages implementation #13
  .travis.yml
  AndroidManifest.xml
  SOEN390-Docs/screenshot-mockup.png
  build.gradle
  captures/org.thoughtcrime.securesms_2018.01.31_22.53.li
  captures/org.thoughtcrime.securesms_2018.01.31_22.55.li
  captures/org.thoughtcrime.securesms_2018.01.31_23.05.li
  captures/org.thoughtcrime.securesms_2018.01.31_23.43.li
  captures/org.thoughtcrime.securesms_2018.02.06_03.32.li
  res/drawable/ic_pin_24dp.xml
  res/drawable/ic_unpin.png
  res/drawable/pinned_message_bubble.xml
  res/layout/pinned_conversation_item_sent.xml
  res/layout/pinned_message_activity.xml
  res/layout/pinned_message_fragment.xml
  res/layout/pinned_message_item.xml
  res/menu/conversation.xml
  res/menu/conversation_context.xml
  res/values/attrs.xml
  res/values/strings.xml
  res/values/themes.xml
  src/org/thoughtcrime/securesms/ApplicationContext.java
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/OnSwipeTouchListener.java
  src/org/thoughtcrime/securesms/PinMessagesLoader.java
  src/org/thoughtcrime/securesms/PinnedMessageActivity.java
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
  src/org/thoughtcrime/securesms/PinnedMessageFragment.java
  src/org/thoughtcrime/securesms/PinnedMessageItem.java
  src/org/thoughtcrime/securesms/PinnedMessagesHandler.java
  src/org/thoughtcrime/securesms/database/DatabaseFactory.java
  src/org/thoughtcrime/securesms/database/MessagingDatabase.java
  src/org/thoughtcrime/securesms/database/MmsDatabase.java
  src/org/thoughtcrime/securesms/database/MmsSmsColumns.java
  src/org/thoughtcrime/securesms/database/MmsSmsDatabase.java
  src/org/thoughtcrime/securesms/database/SmsDatabase.java
  test/androidTest/java/org/thoughtcrime/securesms/PinnedMessageEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/util/SaveAttachmentTaskTest.java
  test/unitTest/java/org/thoughtcrime/securesms/BaseUnitTest.java
  test/unitTest/java/org/thoughtcrime/securesms/PinnedMessagesMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/database/PinnedMessagesTest.java
  test/unitTest/java/org/thoughtcrime/securesms/pinmessages/PinnedMesssagesHandlerTests.java
Labels: in progress

#43 Number fallback on pinned message view
  .gitignore
  captures/org.thoughtcrime.securesms_2018.01.31_22.53.li
  captures/org.thoughtcrime.securesms_2018.01.31_22.55.li
  captures/org.thoughtcrime.securesms_2018.01.31_23.05.li
  captures/org.thoughtcrime.securesms_2018.01.31_23.43.li
  captures/org.thoughtcrime.securesms_2018.02.06_03.32.li
  res/layout/pinned_conversation_item_sent.xml
  res/values/strings.xml
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
Labels: in progress, user story

#44 UI test framework
  build.gradle
  test/androidTest/java/org/thoughtcrime/securesms/PinnedMessageEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/Helper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PinnedHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewActions.java
Labels: in progress, testing

#45 Sprint 3 Mockups
  SOEN390-Docs/nickname-mockup/Chat_Page.JPG
  SOEN390-Docs/nickname-mockup/Chat_Settings.JPG
  SOEN390-Docs/nickname-mockup/Chat_Settings_Default.JPG
  SOEN390-Docs/nickname-mockup/Conversation_Page.JPG
  SOEN390-Docs/nickname-mockup/New_Message.JPG
  SOEN390-Docs/nickname-mockup/Pinned_Messages.JPG
  SOEN390-Docs/pinned-message-UI-mockups/chat_page_pinned_msg_indicator.jpg
  SOEN390-Docs/pinned-message-UI-mockups/pinned_message_image.jpeg
  SOEN390-Docs/pinned-message-UI-mockups/pinned_message_view_new_look.jpg
Labels: in progress

#47 Nickname database
  src/org/thoughtcrime/securesms/NicknameHandler.java
  src/org/thoughtcrime/securesms/database/DatabaseFactory.java
  src/org/thoughtcrime/securesms/database/RecipientDatabase.java
  test/unitTest/java/org/thoughtcrime/securesms/NicknameMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/PinnedMessagesMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/database/NicknameTests.java
  test/unitTest/java/org/thoughtcrime/securesms/database/PinnedMessagesTest.java
  test/unitTest/java/org/thoughtcrime/securesms/nickname/NicknameHandlerTests.java
Labels: in progress
