Repository Radu-Raicea/SignalAndroid, pull requests merged in 2018-03, with the labels that each got.

#52 Better pinned ui
  build.gradle
  res/drawable/pinned_message_bubble.xml
  res/layout/pinned_conversation_item.xml
  res/layout/pinned_conversation_item_sent.xml
  res/layout/pinned_message_fragment.xml
  res/values/colors.xml
  res/values/material_colors.xml
  res/values/strings.xml
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PinnedHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewActions.java
Labels: in progress

#49 Pinned message indicator
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_sent.xml
  res/values/strings.xml
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/PinnedMessagesHandler.java
  src/org/thoughtcrime/securesms/database/MessagingDatabase.java
  src/org/thoughtcrime/securesms/database/MmsDatabase.java
  src/org/thoughtcrime/securesms/database/MmsSmsColumns.java
  src/org/thoughtcrime/securesms/database/SmsDatabase.java
  src/org/thoughtcrime/securesms/database/model/MessageRecord.java
  test/androidTest/java/org/thoughtcrime/securesms/PinnedMessageEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseRecyclerHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewMatchers.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/VisibleErr.java
  test/unitTest/java/org/thoughtcrime/securesms/pinmessages/PinnedMessagesHandlerTests.java
Labels: in progress

#53 Image mms pinned messages
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_sent.xml
  res/layout/pinned_conversation_item.xml
  res/layout/pinned_conversation_item_sent_thumbnail.xml
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
  src/org/thoughtcrime/securesms/PinnedMessageFragment.java
  src/org/thoughtcrime/securesms/PinnedMessageHandler.java
  src/org/thoughtcrime/securesms/PinnedMessageLoader.java
  test/androidTest/java/org/thoughtcrime/securesms/PinnedMessageEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseRecyclerHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/Helper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/HelperSecret.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PinnedHelper.java
  test/unitTest/java/org/thoughtcrime/securesms/PinnedMessageMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/database/PinnedMessageTest.java
  test/unitTest/java/org/thoughtcrime/securesms/pinmessages/PinnedMessageHandlerTests.java
  test/unitTest/java/org/thoughtcrime/securesms/pinmessages/PinnedMesssageHandlerTests.java
Labels: in progress

#56 Nickname ui
  res/layout/group_create_activity.xml
  res/values/strings.xml
  res/xml/recipient_preferences.xml
  src/org/thoughtcrime/securesms/NicknameHandler.java
  src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java
  src/org/thoughtcrime/securesms/database/RecipientDatabase.java
  src/org/thoughtcrime/securesms/recipients/Recipient.java
  test/androidTest/java/org/thoughtcrime/securesms/NicknameEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PreferencesHelper.java
  test/unitTest/java/org/thoughtcrime/securesms/NicknameMocks.java
Labels: in progress

#59 Nickname bug
  src/org/thoughtcrime/securesms/NicknameHandler.java
  src/org/thoughtcrime/securesms/database/DatabaseFactory.java
  src/org/thoughtcrime/securesms/database/RecipientDatabase.java
  src/org/thoughtcrime/securesms/recipients/Recipient.java
  src/org/thoughtcrime/securesms/recipients/RecipientProvider.java
  test/unitTest/java/org/thoughtcrime/securesms/NicknameMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/database/NicknameTests.java
  test/unitTest/java/org/thoughtcrime/securesms/nickname/NicknameHandlerTests.java
Labels: PR, bug-fix, testing

#61 # related to #34, #35, #36 : Unit tests to capture set/change/remove …
  src/org/thoughtcrime/securesms/recipients/Recipient.java
  src/org/thoughtcrime/securesms/recipients/RecipientProvider.java
  test/unitTest/java/org/thoughtcrime/securesms/nickname/RecipientGetterSetterTests.java
Labels: PR, testing

#65 Bug fix #55: Pinning self text messages in groupchat
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
Labels: Pin Messages, bug-fix, in progress

#79 Pin message video audio attachments
  res/layout/pinned_conversation_item.xml
  res/layout/pinned_conversation_item_sent_audio.xml
  res/layout/pinned_conversation_item_sent_document.xml
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
Labels: PR, Pin Messages, testing

#81 added mockups for the pinned messages of different types in conversat…
  SOEN390-Docs/pinned-message-UI-mockups/display_pinned_video.jpg
  SOEN390-Docs/pinned-message-UI-mockups/full_pinned_functionality_group_chat.jpg
  SOEN390-Docs/pinned-message-UI-mockups/pinned_audio_document.jpg
  SOEN390-Docs/pinned-message-UI-mockups/pinned_video.jpg
Labels: PR, in progress

#84 nickname ui test fix
  res/xml/recipient_preferences.xml
  test/androidTest/java/org/thoughtcrime/securesms/NicknameEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PreferencesHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewActions.java
Labels: bug-fix, in progress

#88 related to #87 : Major pinnedmessageAdapter update - critical update
  res/layout/pinned_conversation_item.xml
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
Labels: PR, bug-fix, in progress

#89 Pinmessages ui tests - related to stories #54, #63, #85, #87
  res/layout/pinned_conversation_item.xml
  src/org/thoughtcrime/securesms/PinnedMessageAdapter.java
  test/androidTest/java/org/thoughtcrime/securesms/NicknameEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/PinnedMessageEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PreferencesHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewActions.java
Labels: PR, Pin Messages, bug-fix, in progress

#90 Search integration #66 and #73
  .travis.yml
  SOEN390-Docs/Detailed Diagrams/SearchConversation/ConversationActivity.jpg
  SOEN390-Docs/Detailed Diagrams/SearchConversation/ConversationAdapter.jpg
  SOEN390-Docs/Detailed Diagrams/SearchConversation/ConversationFragment.jpg
  SOEN390-Docs/Detailed Diagrams/SearchConversation/SearchHandler.jpg
  build.gradle
  gradle.properties
  res/drawable/down.png
  res/drawable/up.png
  res/layout/conversation_activity.xml
  res/layout/conversation_search_bottom.xml
  res/menu/conversation.xml
  res/menu/options_menu.xml
  res/values/strings.xml
  src/org/thoughtcrime/securesms/BindableConversationItem.java
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationAdapter.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/ConversationUpdateItem.java
  src/org/thoughtcrime/securesms/SearchHandler.java
  src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java
  test/unitTest/java/org/thoughtcrime/securesms/SearchConversationMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/searchconversation/SearchHandlerTests.java
Labels: in progress, search

#94 related to #93 : Fixed the branch-merge generated bug
  src/org/thoughtcrime/securesms/ConversationFragment.java
Labels: PR, bug, in progress

#91 #89 fix group tests
  test/androidTest/java/org/thoughtcrime/securesms/NicknameEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/PinnedMessageEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/PreferencesHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewActions.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewMatchers.java
Labels: in progress

#95 related to #93 #73 #66: Fixed the branch-merge generated bug
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/SearchHandler.java
Labels: bug-fix, in progress

#96 fixed new message search bug
  src/org/thoughtcrime/securesms/SearchHandler.java
Labels: PR, in progress

#118 Search ui tests
  test/androidTest/java/org/thoughtcrime/securesms/SearchEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseRecyclerHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/SearchHelper.java
Labels: in progress
