Repository Radu-Raicea/SignalAndroid, pull requests merged in 2018-04, with the labels that each got.

#135 #105 added doc about message sync process
  SOEN390-Docs/MessageSynchronization.md
Labels: in progress

#134 Reaction integration
  build.gradle
  res/drawable/ic_emoji.png
  res/drawable/reaction_bubble.xml
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_sent.xml
  res/menu/conversation_context.xml
  res/values/attrs.xml
  res/values/strings.xml
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationAdapter.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/ReactionsHandler.java
  src/org/thoughtcrime/securesms/components/emoji/EmojiDrawer.java
  src/org/thoughtcrime/securesms/components/emoji/EmojiPageView.java
  src/org/thoughtcrime/securesms/database/DatabaseFactory.java
  src/org/thoughtcrime/securesms/database/EncryptingSmsDatabase.java
  src/org/thoughtcrime/securesms/database/IdentityDatabase.java
  src/org/thoughtcrime/securesms/database/MessageReactionDatabase.java
  src/org/thoughtcrime/securesms/database/MmsDatabase.java
  src/org/thoughtcrime/securesms/database/MmsSmsColumns.java
  src/org/thoughtcrime/securesms/database/MmsSmsDatabase.java
  src/org/thoughtcrime/securesms/database/SmsDatabase.java
  src/org/thoughtcrime/securesms/database/model/MediaMmsMessageRecord.java
  src/org/thoughtcrime/securesms/database/model/MessageRecord.java
  src/org/thoughtcrime/securesms/database/model/MmsMessageRecord.java
  src/org/thoughtcrime/securesms/database/model/NotificationMmsMessageRecord.java
  src/org/thoughtcrime/securesms/database/model/SmsMessageRecord.java
  src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
  src/org/thoughtcrime/securesms/jobs/PushTextSendJob.java
  src/org/thoughtcrime/securesms/sms/MessageSender.java
  src/org/thoughtcrime/securesms/util/MessageHash.java
  tools/checkstyle-module.xml
  tools/findbugs-excludes.xml
  tools/pmd-rules.xml
Labels: PR, in progress

#141 type parser
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/database/SmsDatabase.java
  src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
  src/org/thoughtcrime/securesms/util/Stereotype.java
  test/unitTest/java/org/thoughtcrime/securesms/util/StereotypeTest.java
Labels: Message Reactions, in progress

#150 Improve emoji UI and ability to react by clicking on a reaction
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_sent.xml
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/database/MessageReactionDatabase.java
Labels: Message Reactions, PR, in progress

#154 #116 #114 reactions ui test
  test/androidTest/java/org/thoughtcrime/securesms/ReactionEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/BaseRecyclerHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ViewMatchers.java
Labels: in progress

#158 Added Radu's mockups to repo
  SOEN390-Docs/compression-mockups/compress-settings-checkboxes.jpeg
  SOEN390-Docs/compression-mockups/compress-settings.jpeg
  SOEN390-Docs/message-reaction-mockups/emoji-keyboard.jpg
  SOEN390-Docs/message-reaction-mockups/reaction-long-click-option.jpg
  SOEN390-Docs/message-reaction-mockups/reactions-under-message.jpg
  SOEN390-Docs/message-response-mockups/message-response-long-click-option.jpeg
  SOEN390-Docs/message-response-mockups/message-response-ui.jpeg
  SOEN390-Docs/search-mockups/search-option.jpg
  SOEN390-Docs/search-mockups/search-ui.jpg
Labels: in progress

#156 Related to #155. general code quality improvements
  res/values/strings.xml
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/database/DatabaseFactory.java
Labels: PR, code quality, in progress

#160 Message Reply UI test
  test/androidTest/java/org/thoughtcrime/securesms/RepliesEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
Labels: in progress

#157 Unit Tests for Messages Reactions and Replies
  src/org/thoughtcrime/securesms/ReactionsHandler.java
  src/org/thoughtcrime/securesms/RepliesHandler.java
  test/unitTest/java/org/thoughtcrime/securesms/MessageReplyMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/ReactionsMocks.java
  test/unitTest/java/org/thoughtcrime/securesms/messagereactions/ReactionsHandlerTests.java
  test/unitTest/java/org/thoughtcrime/securesms/messagereplies/RepliesHandlerTests.java
Labels: in progress

#159 compression implementation
  .travis.yml
  AndroidManifest.xml
  README.md
  build.gradle
  gradle.properties
  proguard.cfg
  res/values/arrays.xml
  res/values/strings.xml
  res/xml/preferences_chats.xml
  src/org/thoughtcrime/securesms/jobs/SendJob.java
  src/org/thoughtcrime/securesms/mms/MediaConstraints.java
  src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
  src/org/thoughtcrime/securesms/util/MediaUtil.java
  src/org/thoughtcrime/securesms/util/TextSecurePreferences.java
  test/androidTest/java/org/thoughtcrime/securesms/CompressionEspressoTest.java
  test/androidTest/java/org/thoughtcrime/securesms/database/AttachmentDatabaseTest.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ChatsAndMediaSettingsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationSettingsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/ConversationsHelper.java
  test/androidTest/java/org/thoughtcrime/securesms/espresso/SettingsHelper.java
  test/unitTest/java/org/thoughtcrime/securesms/compression/CompressionTest.java
  test/unitTest/java/org/thoughtcrime/securesms/resources/test-img-compressed.jpg
  test/unitTest/java/org/thoughtcrime/securesms/resources/test-img.jpg
  test/unitTest/java/org/thoughtcrime/securesms/resources/test-video-compressed.mp4
  test/unitTest/java/org/thoughtcrime/securesms/resources/test-video.mp4
Labels: Compression, in progress

#163 Related to #144: Added 'send' button in IME when sending replies. Als…
  res/layout/conversation_activity.xml
  res/values/strings.xml
  src/org/thoughtcrime/securesms/ConversationActivity.java
Labels: Message Responses, PR, in progress

#164 Related to #104: Added the missing MessageHash class unit tests
  test/unitTest/java/org/thoughtcrime/securesms/messagehash/MessageHashTest.java
Labels: PR, in progress

#165 syntax and minor code fixes
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/database/MessageReactionDatabase.java
  src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
Labels: in progress

#167 General quality
  src/org/thoughtcrime/securesms/database/MessageReactionDatabase.java
  src/org/thoughtcrime/securesms/database/MessageReplyDatabase.java
Labels: in progress

#168 Message Replies UI Improvement
  res/layout/reply_conversation_item.xml
  src/org/thoughtcrime/securesms/ConversationItem.java
Labels: in progress

#169 Release 2 and Release 3 Diagrams are added to the SOEN390-Docs
  SOEN390-Docs/Release 2 UML Diagrams/Nickname.jpg
  SOEN390-Docs/Release 2 UML Diagrams/Pinned.jpg
  SOEN390-Docs/Release 2 UML Diagrams/UI test.jpg
  SOEN390-Docs/Release 2 UML Diagrams/UnitTest.jpg
  SOEN390-Docs/Release 3 UML Diagrams/Handlers.jpg
  SOEN390-Docs/Release 3 UML Diagrams/release 3 unit tests.jpg
  SOEN390-Docs/jacocoDebugReport.zip
  test/unitTest/java/org/thoughtcrime/securesms/messagehash/MessageHashTest.java
  test/unitTest/java/org/thoughtcrime/securesms/pinmessages/PinnedMesssageHandlerTests.java
Labels: in progress
